#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

MAIN_WORKTREE="$(git worktree list --porcelain | awk 'NR==1 {print $2}')"
export MAIN_WORKTREE
node "${MAIN_WORKTREE}/node_modules/.bin/lint-staged" --verbose
